spring:
  application:
    name: "configServer"
  cloud:
    config:
      server:git:
          uri: "https://github.com/kennyowj961127/SpringBootConfigServer.git"
          default-label: "master"
          timeout: 5
          clone-on-start: true
          force-pull: true
server:
  port: 8071